### ISSUE TITLE
Problem on run

### ISSUE THREAD

**Issue by alexroumi** [brentvollebregt/whos-on-my-network#1]
When I start it it always says that it can't get devices because it can't connect to the server

**Comment by brentvollebregt** [comment]
How are you running the project?

**Comment by alexroumi** [comment]
`python -m whos_on_my_network start`

**Comment by brentvollebregt** [comment]
Are there any errors you can see anywhere? If you go into dev tools, why did the request fail?

**Comment by alexroumi** [comment]
these are my errors

![Screenshot 2021-01-21 200144](https://user-images.githubusercontent.com/59561790/105392137-8894dc80-5c23-11eb-9d83-51a0a0cf2399.png)

**Comment by brentvollebregt** [comment]
`/api/person` got a HTTP 500 - can you take a look at the error in dev tools? Also you should be able to see it in the console running the server.

**Comment by alexroumi** [comment]
In the console there aren't any details

My Console

![Screenshot 2021-01-21 200817](https://user-images.githubusercontent.com/59561790/105392964-79625e80-5c24-11eb-8700-b3bdef8e9fba.png)

**Comment by brentvollebregt** [comment]
What version of peewee do you currently have installed? 
If you install peewee 3.13.1, does this fix it?

Looks like coleifer/peewee#2317 might shed some light on this.

**Comment by alexroumi** [comment]
thank you so much it was the version of peewee (3.14.0) when I uninstalled it and installed 3.13.1 it worked perfectly fine.

**Comment by brentvollebregt** [comment]
2.2.2 now contains the fix. Thanks for helping with this.
