### ISSUE TITLE
Is it possible to deploy it on a docker container

### ISSUE THREAD

**Issue by alexroumi** [brentvollebregt/whos-on-my-network#12]
Hi so i want to deploy this on a docker container but I am new to this stuff and I don't know if it is even possible can anyone help?

**Comment by brentvollebregt** [comment]
Yes, this could be deployed to a docker container. This project does not have a Dockerfile yet though.

**Comment by alexroumi** [comment]
Could you please guide me on how to do it?

**Comment by brentvollebregt** [comment]
Docker has a getting started tutorial at https://docs.docker.com/get-started/

**Comment by brentvollebregt** [comment]
The application now runs in a docker container - see README for details
