### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Fabxx** [brentvollebregt/whos-on-my-network#13]
trying to run this from linux, webapp works but when i try to scan it says npcap is required, tho there's nmap available already.

**Comment by brentvollebregt** [comment]
It looks like for Linux, you will need `tcpdump` as [noted here](https://scapy.readthedocs.io/en/latest/installation.html#platform-specific-instructions).

I'm not sure what flavour you are running but following the "Platform-specific instructions" from that link above might get you running.

**Comment by Prox-y** [comment]
I'm using kali distro which should have all of that already

**Comment by brentvollebregt** [comment]
Kali is based on Debian - if you execute `tcpdump` in the terminal, does it work?

**Comment by revix-0** [comment]
yes

**Comment by revix-0** [comment]
it's useless to do it since it's already installed, no changes are made when doing it

**Comment by brentvollebregt** [comment]
Are you able to provide the traceback and error?

**Comment by revix-0** [comment]
there's no error, it just asks for npcap and i can't continue. Are you sure the program looks for other alternatives rather than npcap?

**Comment by brentvollebregt** [comment]
Right, I see you are getting [this error here, in the except blocks](https://github.com/brentvollebregt/whos-on-my-network/blob/b77cd5ec462571a0c1f75e9105d8d90c740a79cc/whos_on_my_network/service/scanning.py#L31).

In a Python shell, if you execute:

```python
from scapy.all import arping
result, _ = arping('192.168.1.1', verbose=0)
```

Do you get any errors? If so, what are they?

**Comment by brentvollebregt** [comment]
Are you able to debug the application? If you put breakpoints on:

- [whos_on_my_network/service/scanning.py line 31](https://github.com/brentvollebregt/whos-on-my-network/blob/master/whos_on_my_network/service/scanning.py#L31)
- [whos_on_my_network/service/scanning.py line 34](https://github.com/brentvollebregt/whos-on-my-network/blob/master/whos_on_my_network/service/scanning.py#L34)

What is in the variable `exception`? (this is in both except blocks).

**Comment by brentvollebregt** [comment]
These exceptions should now be shown in the output

**Comment by brentvollebregt** [comment]
The docker file uses Linux - this tool works on Linux
