### ISSUE TITLE
Npcap issue VM/WSL

### ISSUE THREAD

**Issue by snuxs** [brentvollebregt/whos-on-my-network#29]
Hello, I installed the tool on WSL and got  "Npcap must be installed for windows host" 
Afterwards I installed it in VMware on Ubuntu and got the same issue.
I installed Npcap on the host machine windows but it does not help.
What am I missing?

**Comment by brentvollebregt** [comment]
Have you taken a look at #13? It also talks about npcap missing on Linux hosts.

**Comment by brentvollebregt** [comment]
I've added more logging in the default scanner to give some more context. I'll close this since it's been open for a while though but we can re-open if wanted.
