### ISSUE TITLE
Help me install this

### ISSUE THREAD

**Issue by astronyu** [brentvollebregt/whos-on-my-network#30]
May I ask how to install this on windows really?
I followed the instructions up until I got to this commane: "Build the webapp: cd webapp && npm i && npm run build"
There was no webapp folder so the command failed.

**Comment by brentvollebregt** [comment]
If you look at [the files in the root of the repo](https://github.com/brentvollebregt/whos-on-my-network), there is definitely a webapp folder. Make sure you are running the command from the root of the source.

**Comment by astronyu** [comment]
Thank you. I've redownload and run them and now it seems to work.
I must say this is a good script, would love to see a docker version in the future.
Can the script list out type of device based on the mac address? Reason I tried this script is to look if it supports it.

**Comment by brentvollebregt** [comment]
> Does "name" and "owner" field only works if we use plugin to communicate direct with a router?

No, these are manual fields you need to set using the UI

> I can see it can detect vendor as well, any chance to add this in home page?

The home page is currently used to display devices

> Can the script list out type of device based on the mac address?

Vendor detection is only done client side and device type is not obtained at all - so not currently
